import Head from "next/head";
import { Container } from "postcss";

        
export default function Arm() {
    return (
        <div  >
            <Head>
                <title> Business | JONGKEW </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <div>
                    ยินดีต้อนรับ
                <h1> JONGKEW </h1>
                </div>
                    
               
            </main>


        </div>
    )
}
